trigger:
  branches:
    include:
    - master
    - validate/*
    - release/*
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  codecov_token: f604a7c4-d19b-4f4d-b160-c9057e8f6b33
  ci_feed: /e08c98c0-63d6-4dc6-80ca-944e4deaf3d2

jobs:
- template: azure-pipelines/build.yml
